FROM python:3.6-alpine

RUN apk update && apk add postgresql-dev gcc g++ python3-dev musl-dev bash git libffi-dev make

ENV FLASK_ENV=production

WORKDIR /usr/src/app

COPY . .

RUN pip install -r requirements.txt
RUN pip install --upgrade -e .

EXPOSE 5000
EXPOSE 80
EXPOSE 8001

CMD [ "gunicorn", "app.factory:application", "-w", "4", "-b", "0.0.0.0:8001" ]
