version: '3'
services:
  app:
    hostname: supportservice.prod
    image: levlaz/supportservice
    environment:
      - FLASK_APP=run.py
      - DATABASE_URL=$DATABASE_URL
      - FLASK_ENV=production
      - LD_CLIENT_KEY=$LD_CLIENT_KEY
      - LD_FRONTEND_KEY=$LD_FRONTEND_KEY
    ports:
      - "8000:8000"
    command: ./scripts/start.sh
    depends_on:
      - db
      - cache
    
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=supportService
      - POSTGRES_PASSWORD=supportService
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis
    ports:
      - "6379:6379"
  
  web:
    image: nginx
    volumes: 
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app