FROM python:3.6-alpine

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev bash git

WORKDIR /usr/src/app

COPY . .

RUN pip install --upgrade -e .
RUN pip install -e lib/api-client-python