# coding: utf-8

"""
    LaunchDarkly REST API

    Build custom integrations with the LaunchDarkly REST API  # noqa: E501

    OpenAPI spec version: 2.0.9
    Contact: support@launchdarkly.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import launchdarkly_api
from launchdarkly_api.models.feature_flag_statuses import FeatureFlagStatuses  # noqa: E501
from launchdarkly_api.rest import ApiException


class TestFeatureFlagStatuses(unittest.TestCase):
    """FeatureFlagStatuses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeatureFlagStatuses(self):
        """Test FeatureFlagStatuses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = launchdarkly_api.models.feature_flag_statuses.FeatureFlagStatuses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
