name: Run Selenium Simulator
# on:
#   schedule:
#     - cron: '0 * * * *'
on: push
jobs:
  simualte:
    name: Simulate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
      - name: Install Simulator
        run: |
          cd tests/webdriver
          mvn compile assembly:single
      - name: Run Simulation
        env:
          LD_API_KEY: ${{ secrets.LD_API_KEY }}
          LD_CLIENT_KEY: ${{ secrets.LD_CLIENT_KEY }}
        run: |
          cd tests/webdriver
          java -jar target/webdriver-1.0-SNAPSHOT-jar-with-dependencies.jar
